// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTUVrGBDBceemQ-9soG8sR4c7NEnywCfo',
    appId: '1:670433190201:web:92d6fb5e2c31359cf688e8',
    messagingSenderId: '670433190201',
    projectId: 'asdqwe-18a92',
    authDomain: 'asdqwe-18a92.firebaseapp.com',
    databaseURL: 'https://asdqwe-18a92-default-rtdb.firebaseio.com',
    storageBucket: 'asdqwe-18a92.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzko4sCgxz9BQgO6dHLVEkhlPgnxD0Sag',
    appId: '1:670433190201:android:5455e5b0ed89eaa6f688e8',
    messagingSenderId: '670433190201',
    projectId: 'asdqwe-18a92',
    databaseURL: 'https://asdqwe-18a92-default-rtdb.firebaseio.com',
    storageBucket: 'asdqwe-18a92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAomDPAuV7rhnxGcg7_Ja2YL7RHWZbJCm8',
    appId: '1:670433190201:ios:5060034a8dccfb1ff688e8',
    messagingSenderId: '670433190201',
    projectId: 'asdqwe-18a92',
    databaseURL: 'https://asdqwe-18a92-default-rtdb.firebaseio.com',
    storageBucket: 'asdqwe-18a92.appspot.com',
    iosBundleId: 'com.flutterflow.healthai',
  );
}
